# Generated by Django 4.2.30 on 2026-09-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.URLField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('almacenamiento', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=255)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
